### ISSUE TITLE
Include Panic and Evade on Right Click Options

### ISSUE THREAD

**Issue by ArkeinGuardia** [ArkeinGuardia/Triumph_TTS#85]

**Comment by marcpawl** [comment]
Why given the chance that a straight move will not take place, and we have a way to do this already.

84.1 Panic
a: fall back (fall back)
b. turn around (turn around)
c. full tactical move (move)

though we could halt the movement if we meet anything, since the base is destroyed. (84.2)

83 Evade is tricker since the base is not destroyed on collisions
a.  Fall back (fall back)
b move back 4MU (move back single, repeatedly)

**Comment by marcpawl** [comment]
done.  Bases will stop when colliding with another base.
